- name: Launch a compute instance
  hosts: localhost

  tasks:
  - name: Launch a VM
    os_server:
      name: "{{ item.name }}"
      image: "{{ item.image }}"
      key_name: "{{ item.key_name }}"
      availability_zone: nova
      flavor: "{{ item.flavor}}"
      state: present
      security_groups: "{{ item.security_group }}"
      meta: "group={{ item.group }}"
      auto_ip: no
    register: server
    with_items:
      - { name: "{{ lookup('env', 'OS_VM_NAME') }}", image: "{{ lookup('env', 'OS_IMAGE') }}", flavor: "{{ lookup('env', 'OS_FLAVOR') }}", security_group: "{{ lookup('env', 'OS_SECURITY_GROUP') }}", key_name: "{{ lookup('env', 'OS_KEY_NAME') }}",  group: 'node' }

  - name: Wait for SSH on the Instance
    command: >
      ssh -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@{{item.server.private_v4}} true
    with_items: "{{ server.results }}"
    register: result
    until: result is success
    retries: 30
    delay: 10

  - name: Add VM to inventory
    add_host:
      name: "{{ item.server.name }}"
      groups: "{{ item.server.metadata.group }}"
      ansible_host: "{{ item.server.private_v4 }}"
    with_items: "{{ server.results }}"


- import_playbook: deploy_k8s.yaml

