- name: Launch a compute instance
  hosts: localhost
  tasks:
  - name: Launch a VM
     os_server:
      name: "{{ item.name }}"
      image: "{{ item.image }}"
      key_name: "{{ item.key_name }}"
      availability_zone: nova
      flavor: "{{ item.flavor}}"
      state: present
      security_groups: "{{ item.security_group }}"
      meta: "group={{ item.group }}"
      auto_ip: no
    register: my_vm
    with_items:
      - { name: 'kube_master', image: 'ubuntu_18.04', flavor: 'cldareapd.4cores4GB25GB', security_group: 'k8s-nodes', key_name: 'Lisa',  group: 'master' }
      - { name: 'kube_node1', image: 'ubuntu_18.04', flavor: 'cldareapd.4cores4GB25GB', security_group: 'k8s-nodes', key_name: 'Lisa',  group: 'node' }

  - name: Add VM to inventory
    add_host:
      name: "{{ item.server.name }}"
      groups: "{{ item.server.metadata.group }}"
      ansible_host: "{{ item.server.private_v4 }}"
    with_items: "{{ my_vm.results }}"

  # Don't assume the inventory_hostname is resolvable and delay 40 seconds at start
  - name: Wait for the SSH connection"
    wait_for:
       port: 22
       host: "{{ item.server.private_v4 }}"
       delay: 40
       state: started
    with_items: "{{ my_vm.results }}"
    connection: local

- import_playbook: deploy_k8s.yaml


- name: Install Keystone authentication webhook
  hosts: master
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - auth/keystone
