# Set the OS authentication (do not change if using CloudVeneto)
OS_AUTH_URL: https://keystone-cv.pd.infn.it/v3
OS_IDENTITY_API_VERSION: 3
OS_REGION_NAME: regionOne
OS_INTERFACE: public
OS_CACERT: /etc/pki/tls/certs/ca-bundle.crt
# change the value below only if you want to use an already existing security group
OS_SECURITY_GROUP: K8S-SG

# The OS authentication type (password | token)
OS_AUTH_TYPE: password

# The OS user credential using OS_AUTH_TYPE: password
OS_USERNAME: <your_username>
OS_PASSWORD: <your_password>

# The OS user credential using OS_AUTH_TYPE: token (good for use with EGI Federated cloud)
# VOMS_PROXY and EGI_CHECKIN are mutually exclusive.
#VOMS_PROXY: <your-proxy-filename> (e.g. /tmp/x509up_u1000)

#EGI_CHECKIN_URL: https://aai.egi.eu
#EGI_CHECKIN_CLIENT_ID: <your-client-id> (taken from https://aai.egi.eu/fedcloud)
#EGI_CHECKIN_CLIENT_SECRET: <your-client-secret> (taken from https://aai.egi.eu/fedcloud)
#EGI_CHECKIN_REFRESH_TOKEN: <your-refresh-token> (taken from https://aai.egi.eu/fedcloud)

# Set the user key pair
# Create a new key pair with the user public key if specified
# To generate the keys use: ssh-keygen -t rsa -f cloud.key (without password)
# If your key is already available in OpenStack, just set its name in OS_KEY_NAME and the private key filename in OS_KEY_PRIVATE   
OS_KEY_NAME: my_key
OS_KEY_PUBLIC: cloud.key.pub
OS_KEY_PRIVATE: cloud.key

# Set the project (pre-defined values below are for CMS project, change them according with your project)
OS_PROJECT_NAME: CMS
OS_PROJECT_ID: d27fe2becea94a3e980fb9f66e2f291a
OS_PROJECT_DOMAIN_NAME: default
OS_USER_DOMAIN_NAME: default
OS_NETWORK: CMS-lan

# Set the public IP address (auto | IPv4 address), not necessary for CloudVeneto
#OS_FIP: auto

# Set the name, image and flavor of the K8S master (image and flavor defaults below are a good start):
# a flavor with a minumum of 2 VCPUs and 4 GB of VRAM is required for the master
# be sure to choose a master VM name unique within your project 
OS_MASTER_NAME: <choose-a-master-name>
OS_MASTER_IMAGE: Ubuntu-xenial
OS_MASTER_FLAVOR: cloudveneto.medium

# Set the name, image and flavor of the K8S nodes (image and flavor defaults below are a good start)
OS_NODE_NAME: <choose-a-node-name-prefix>
OS_NODE_IMAGE: Ubuntu-xenial
OS_NODE_FLAVOR: cloudveneto.large

# Set the number of K8S nodes to create (with 3 nodes and defaults above you'll have a cluster with 12 VCPUs)
OS_NODES: 3
