---

- name: Install kafka operator
  vars:
    projectns: default
    strimziver: 0.14.0
  become: no
  block:
    - unarchive:
        remote_src: yes
        src: https://github.com/strimzi/strimzi-kafka-operator/releases/download/{{ strimziver }}/strimzi-{{ strimziver }}.tar.gz
        dest: ./
    - find:
        paths: ./strimzi-{{ strimziver }}/install/cluster-operator
        patterns: '*RoleBinding*.yaml'
      register: rolebindings
    - replace:
        path: "{{ item.path }}"
        regexp: "namespace: .*"
        replace: "namespace: {{ projectns }}"
      with_items: "{{ rolebindings.files }}"
    - replace:
        path: ./strimzi-{{ strimziver }}/install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml
        regexp: 'valueFrom:\n\s+fieldRef:\n\s+fieldPath:\s+metadata.namespace'
        replace: "value: \"*\""
    - command: |
        kubectl --kubeconfig={{ kubeadmin_config }} create clusterrolebinding strimzi-cluster-operator-namespaced --clusterrole=strimzi-cluster-operator-namespaced --serviceaccount {{ projectns }}:strimzi-cluster-operator
    - command: |
        kubectl --kubeconfig={{ kubeadmin_config }} create clusterrolebinding strimzi-cluster-operator-entity-operator-delegation --clusterrole=strimzi-entity-operator --serviceaccount {{ projectns }}:strimzi-cluster-operator
    - command: |
        kubectl --kubeconfig={{ kubeadmin_config }} create clusterrolebinding strimzi-cluster-operator-topic-operator-delegation --clusterrole=strimzi-topic-operator --serviceaccount {{ projectns }}:strimzi-cluster-operator
    - command: |
        kubectl --kubeconfig={{ kubeadmin_config }} apply -f ./strimzi-{{ strimziver }}/install/cluster-operator -n {{ projectns }}
  when:
    inventory_hostname == 'master' or main_cluster_node
  rescue:
    - debug:
        msg: "Cannot deploy Kafka operator"

