apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-keystone-auth
  namespace: kube-system
  labels:
    app: k8s-keystone-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-keystone-auth
  template:
    metadata:
      labels:
        app: k8s-keystone-auth
    spec:
      containers:
        - name: k8s-keystone-auth
          image: k8scloudprovider/k8s-keystone-auth
          imagePullPolicy: Always
          env:
            - name: OS_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: keystone-auth-certs
                  key: os_auth_url
            - name: CACERT_FILE
              valueFrom:
                secretKeyRef:
                  name: keystone-auth-certs
                  key: os_cacert
          args:
            - ./bin/k8s-keystone-auth
            - --tls-cert-file
            - /etc/keystone/pki/cert-file
            - --tls-private-key-file
            - /etc/keystone/pki/key-file
            - --policy-configmap-name
            - k8s-auth-policy
            - --keystone-url
            - "$(OS_AUTH_URL)"
            - --keystone-ca-file
            - "$(CACERT_FILE)"
          volumeMounts:
            - mountPath: /etc/keystone/pki
              name: keystone-auth-certs
              readOnly: true
          ports:
            - containerPort: 8443
      volumes:
      - name: keystone-auth-certs
        secret:
          secretName: keystone-auth-certs
---
kind: Service
apiVersion: v1
metadata:
  name: k8s-keystone-auth-service
  namespace: kube-system
spec:
  selector:
    app: k8s-keystone-auth
  clusterIP: 10.111.64.132
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
