---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-auth-policy
  namespace: kube-system
data:
  policies: |
    [
      {
        "resource": {
          "verbs": ["get", "list", "watch", "create", "update", "delete"],
          "resources": ["pods"],
          "version": "*",
          "namespace": "default"
        },
        "match": [
          {
            "type": "role",
            "values": ["admin", "_member_"]
          },
          {
            "type": "project",
            "values": ["OS_PROJECT"]
          }
        ]
      },
      {
        "resource": {
            "verbs": ["bind"],
            "resources": ["clusterroles"],
            "resourceNames": ["admin", "edit", "view"],
          "version": "*",
          "namespace": "default"
        },
        "match": [
          {
            "type": "role",
            "values": ["admin"]
          },
          {
            "type": "project",
            "values": ["OS_PROJECT"]
          }
        ]
      }
    ]
