---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-auth-policy
  namespace: kube-system
data:
  policies: |
    [
      {
        "resource": {
          "verbs": ["get", "list", "watch", "create", "update", "delete"],
          "resources": ["pods"],
          "version": "*",
          "namespace": "default"
        },
        "match": [
          {
            "type": "role",
            "values": ["k8s_user"]
          },
          {
            "type": "project",
            "values": ["OS_PROJECT"]
          }
        ]
      },
      {
        "resource": {
            "verbs": ["*"],
            "resources": ["*"],
          "version": "*",
          "namespace": "*"
        },
        "match": [
          {
            "type": "user",
            "values": ["OS_USERNAME"]
          },
          {
            "type": "project",
            "values": ["OS_PROJECT"]
          }
        ]
      }
    ]
