apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: ktopic
  namespace: default
  labels:
    strimzi.io/cluster: kcluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
