apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: smactcluster
  namespace: default
spec:
  kafka:
    replicas: 3
    listeners:
      external:
        type: nodeport
        tls: false
    config:
      cleanup.policy: delete
      delete.topic.enable: true
      group.initial.rebalance.delay.ms: 0
      log.retention.bytes: 1000000000
      log.retention.check.interval.ms: 15000
      log.retention.ms: 30000
      log.segment.bytes: 500000000
      num.io.threads: 8
      num.network.threads: 3
      num.partitions: 1
      num.recovery.threads.per.data.dir: 1
      offsets.topic.replication.factor: 1
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
      socket.send.buffer.bytes: 102400
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
      zookeeper.connection.timeout.ms: 6000
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator:
      watchedNamespace: default
      zookeeperSessionTimeoutSeconds: 60
    userOperator: {}
