apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: produce28partitions
  namespace: default
  labels:
    strimzi.io/cluster: smactcluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: occupancyplot
  namespace: default
  labels:
    strimzi.io/cluster: smactcluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: eventsdataframe
  namespace: default
  labels:
    strimzi.io/cluster: smactcluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
