---

- name: Create the Spark operator namespace
  when: init_cluster and started_kubelet
  command: |
    kubectl --kubeconfig={{ kubeadmin_config }} create namespace spark-operator
  register: create_result
  until: create_result.rc == 0
  retries: 5
  delay: 2

- name: Deploy the Spark operator
  when: init_cluster and started_kubelet
  command: |
    helm --kubeconfig={{ kubeadmin_config }} {{ item }} 
  with_items:
     - "repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator"
     - "install sparkoperator incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default"
  register: create_result
  until: create_result.rc == 0
  retries: 5
  delay: 2

