---
- name: Reset kubeadm before init in case this is not the first run
  when: kubeadm_reset_before_init
  command: kubeadm reset -f


- name: kubeadm join with pre generated token
  command: kubeadm join --token {{ kubeadm_token }} {{ hostvars[groups['master'][0]]['ansible_host'] }}:6443 --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}


- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
