---
- name: Reset kubeadm before init in case this is not the first run
  when: kubeadm_reset_before_init
  command: kubeadm reset -f


- name: kubeadm join with pre generated token
  command: kubeadm join --token {{ kubeadm_token }} {{ lookup("env", "K8S_MASTER_HOST") }}:6443 --discovery-token-ca-cert-hash sha256:{{ lookup("env", "K8S_CA_CERT_HASH") }}


- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
