---

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes
  become_method: sudo

- name: install basic packages
  package: 
    name: ['jq', 'tree', 'python-yaml', 'git', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
  become: yes
  become_method: sudo
