---

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes
  become_method: sudo

# This may require a reboot
#- name: Update all packages to the latest version
#  apt:
#    upgrade: dist
#  become: yes
#  become_method: sudo
  
- name: install basic packages
  apt: package: ['jq', 'tree', 'python-yaml', 'git', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common'] update_cache=yes
  become: yes
  become_method: sudo
