---

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install list of packages
  apt:
    name: ['docker-ce=18.06.0~ce~3-0~ubuntu']
    state: present
    update_cache: yes
    force: yes
    autoremove: yes

- name: add remote user to group docker
  command: usermod -aG docker {{ansible_user}}

- name: Start docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: enable if command above does strange things (debug me)
  command: systemctl enable docker

# This is needed based on Docker 1.13 update. Kubernetes and/or CNI could also fix this.
- name: Re-enable ipchains FORWARD
  iptables:
    chain: FORWARD
    policy: ACCEPT
